python3 domain.py --domain a-c
python3 domain.py --domain a-d
python3 domain.py --domain b-a
python3 domain.py --domain b-c
python3 domain.py --domain b-d
python3 domain.py --domain c-a
python3 domain.py --domain c-b
python3 domain.py --domain c-d
python3 domain.py --domain d-a
python3 domain.py --domain d-b
python3 domain.py --domain d-c