python3 cdomain.py --domain a-b --training_mode TS-TCC
python3 cdomain.py --domain a-c --training_mode TS-TCC
python3 cdomain.py --domain a-d --training_mode TS-TCC
python3 cdomain.py --domain b-a --training_mode TS-TCC
python3 cdomain.py --domain b-c --training_mode TS-TCC
python3 cdomain.py --domain b-d --training_mode TS-TCC
python3 cdomain.py --domain c-a --training_mode TS-TCC
python3 cdomain.py --domain c-b --training_mode TS-TCC
python3 cdomain.py --domain c-d --training_mode TS-TCC
python3 cdomain.py --domain d-a --training_mode TS-TCC
python3 cdomain.py --domain d-b --training_mode TS-TCC
python3 cdomain.py --domain d-c --training_mode TS-TCC

python3 cdomain.py --domain a-b --training_mode SimCLR
python3 cdomain.py --domain a-c --training_mode SimCLR
python3 cdomain.py --domain a-d --training_mode SimCLR
python3 cdomain.py --domain b-a --training_mode SimCLR
python3 cdomain.py --domain b-c --training_mode SimCLR
python3 cdomain.py --domain b-d --training_mode SimCLR
python3 cdomain.py --domain c-a --training_mode SimCLR
python3 cdomain.py --domain c-b --training_mode SimCLR
python3 cdomain.py --domain c-d --training_mode SimCLR
python3 cdomain.py --domain d-a --training_mode SimCLR
python3 cdomain.py --domain d-b --training_mode SimCLR
python3 cdomain.py --domain d-c --training_mode SimCLR

python3 cdomain.py --domain a-b --training_mode CPC
python3 cdomain.py --domain a-c --training_mode CPC
python3 cdomain.py --domain a-d --training_mode CPC
python3 cdomain.py --domain b-a --training_mode CPC
python3 cdomain.py --domain b-c --training_mode CPC
python3 cdomain.py --domain b-d --training_mode CPC
python3 cdomain.py --domain c-a --training_mode CPC
python3 cdomain.py --domain c-b --training_mode CPC
python3 cdomain.py --domain c-d --training_mode CPC
python3 cdomain.py --domain d-a --training_mode CPC
python3 cdomain.py --domain d-b --training_mode CPC
python3 cdomain.py --domain d-c --training_mode CPC